USE meat_business_db;

ALTER TABLE customers
MODIFY COLUMN price_mode
ENUM('COMMON_PRICE','CUSTOM_PRICE','PRIVATE','PRIVATE_PRICE')
NOT NULL DEFAULT 'COMMON_PRICE';

UPDATE customers
SET price_mode='COMMON_PRICE'
WHERE price_mode IS NULL OR price_mode='';

ALTER TABLE customers
ADD COLUMN IF NOT EXISTS parent_customer_id BIGINT NULL;

ALTER TABLE debt_installment_plans
ADD COLUMN IF NOT EXISTS target_debt_amount DECIMAL(15,2) NOT NULL DEFAULT 0;

ALTER TABLE sponsor_ad_campaigns
ADD COLUMN IF NOT EXISTS video_url TEXT NULL,
ADD COLUMN IF NOT EXISTS thumbnail_url TEXT NULL,
ADD COLUMN IF NOT EXISTS del_flg TINYINT(1) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL,
ADD COLUMN IF NOT EXISTS deleted_reason TEXT NULL;
